apiVersion: v1
kind: ReplicationController

metadata:
  name: name_of_replication_controller_pod
  # labels could be any key value pair
  labels:
    key_1: value_1
    key_2: value_2
    
spec:

  # templates contains the metadata and spec of the pod
  template:
    metadata:
      labels:
        key_1: value_1
        key_2: value_2
    spec:
      containers:
      - name: container_name
        image: container_image_url:varsion
        
  # modify replicas according to your case
  replicas: 3
